import type { KitArtifactBannerProps } from "./KitArtifactBanner";
import type { ArtifactSlot } from "./artifactBanners";

/** Карточки товара на кадрах Higgsfield: изделие снято в сцене, текст поверх.
 *  Тёмное изделие -> светлая сцена (onLight), светлое изделие -> тёмная сцена. */
export const HS_CARD_SLOTS: ArtifactSlot[] = [
  {
    id: "hcard-001", width: 1200, height: 1600,
    slot: "Карточка — Шарм подвеска с Метеоритом",
    props: {
      background: "kit-scenes-hs/scene_001.jpg",
      photo: "kit-scenes-hs/scene_001.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Украшения", title: "ПОДВЕСКА",
      subtitle: "оправа ручной работы, метеоритная вставка",
      meta: "Ручная работа · Краснодар", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-002", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Царев (горбушка) 34,5 гр.",
    props: {
      background: "kit-scenes-hs/scene_002.jpg",
      photo: "kit-scenes-hs/scene_002.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "ЦАРЁВ",
      subtitle: "коллекционный образец",
      meta: "Волгоградская область · 1968", note: "Вес: 34,5 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-003", width: 1200, height: 1600,
    slot: "Карточка — Часы наручные женские с метеоритом Муонионалус",
    props: {
      background: "kit-scenes-hs/scene_003.jpg",
      photo: "kit-scenes-hs/scene_003.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Украшения", title: "МУОНИОНАЛУСТА",
      subtitle: "оправа ручной работы, метеоритная вставка",
      meta: "Швеция · 1906", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-004", width: 1200, height: 1600,
    slot: "Карточка — Браслет из натуральных камней с метеоритом Муо",
    props: {
      background: "kit-scenes-hs/scene_004.jpg",
      photo: "kit-scenes-hs/scene_004.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Украшения", title: "МУОНИОНАЛУСТА",
      subtitle: "ручная сборка, натуральный камень и метеорит",
      meta: "Швеция · 1906", note: "Размер подбираем по запястью", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-005", width: 1200, height: 1600,
    slot: "Карточка — Мужской браслет Прометей лабрадорит с метеорит",
    props: {
      background: "kit-scenes-hs/scene_005.jpg",
      photo: "kit-scenes-hs/scene_005.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Украшения", title: "ПРОМЕТЕЙ",
      subtitle: "ручная сборка, натуральный камень и метеорит",
      meta: "Метеорит Aletai · Китай · 1898", note: "Размер подбираем по запястью", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-006", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Дронино железный коллекционный образе",
    props: {
      background: "kit-scenes-hs/scene_006.jpg",
      photo: "kit-scenes-hs/scene_006.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "ДРОНИНО",
      subtitle: "железный метеорит",
      meta: "Рязанская область · 2000", note: "Вес: 27,8 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-007", width: 1200, height: 1600,
    slot: "Карточка — Бусина Дзи 9 глаз метеорит Алетай, золото, аму",
    props: {
      background: "kit-scenes-hs/scene_007.jpg",
      photo: "kit-scenes-hs/scene_007.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Книга небесного железа", title: "ДЕВЯТЬ ГЛАЗ",
      subtitle: "резьба вручную по метеоритному железу",
      meta: "Метеорит Aletai · Китай · 1898", note: "Ручная резьба", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-008", width: 1200, height: 1600,
    slot: "Карточка — Браслет женский Сердце Будды с метеоритом Алет",
    props: {
      background: "kit-scenes-hs/scene_008.jpg",
      photo: "kit-scenes-hs/scene_008.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Украшения", title: "ALETAI",
      subtitle: "ручная сборка, натуральный камень и метеорит",
      meta: "Китай · 1898", note: "Размер подбираем по запястью", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-009", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь железный, образец 55,7 г",
    props: {
      background: "kit-scenes-hs/scene_009.jpg",
      photo: "kit-scenes-hs/scene_009.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "железный метеорит",
      meta: "Приморский край · 1947", note: "Вес: 55,7 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-010", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь железный, образец 31,1 г",
    props: {
      background: "kit-scenes-hs/scene_010.jpg",
      photo: "kit-scenes-hs/scene_010.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "железный метеорит",
      meta: "Приморский край · 1947", note: "Вес: 31,1 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-011", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Дронино железный, коллекционный образ",
    props: {
      background: "kit-scenes-hs/scene_011.jpg",
      photo: "kit-scenes-hs/scene_011.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Коллекционные образцы", title: "ДРОНИНО",
      subtitle: "железный метеорит",
      meta: "Рязанская область · 2000", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-012", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Царёв каменный образец 34 гр, оберег ",
    props: {
      background: "kit-scenes-hs/scene_012.jpg",
      photo: "kit-scenes-hs/scene_012.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "ЦАРЁВ",
      subtitle: "каменный метеорит",
      meta: "Волгоградская область · 1968", note: "Вес: 34 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-013", width: 1200, height: 1600,
    slot: "Карточка — Кулон-амулет паук из индошинита, тектит, обере",
    props: {
      background: "kit-scenes-hs/scene_013.jpg",
      photo: "kit-scenes-hs/scene_013.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Книга небесного железа", title: "ПАУК",
      subtitle: "резьба вручную по метеоритному железу",
      meta: "Индошинит · Юго-Восточная Азия", note: "Ручная резьба", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-014", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь железный, коллекционный ",
    props: {
      background: "kit-scenes-hs/scene_014.jpg",
      photo: "kit-scenes-hs/scene_014.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "железный метеорит",
      meta: "Приморский край · 1947", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-015", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь железный коллекционный, ",
    props: {
      background: "kit-scenes-hs/scene_015.jpg",
      photo: "kit-scenes-hs/scene_015.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "железный метеорит",
      meta: "Приморский край · 1947", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-016", width: 1200, height: 1600,
    slot: "Карточка — Мужской браслет из натуральных камней с метеор",
    props: {
      background: "kit-scenes-hs/scene_016.jpg",
      photo: "kit-scenes-hs/scene_016.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Украшения", title: "ALETAI",
      subtitle: "ручная сборка, натуральный камень и метеорит",
      meta: "Китай · 1898", note: "Размер подбираем по запястью", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-018", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Дронино железный, коллекционный образ",
    props: {
      background: "kit-scenes-hs/scene_018.jpg",
      photo: "kit-scenes-hs/scene_018.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Коллекционные образцы", title: "ДРОНИНО",
      subtitle: "железный метеорит",
      meta: "Рязанская область · 2000", note: "Вес: 62,1 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-019", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь железный, коллекционный ",
    props: {
      background: "kit-scenes-hs/scene_019.jpg",
      photo: "kit-scenes-hs/scene_019.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "железный метеорит",
      meta: "Приморский край · 1947", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-020", width: 1200, height: 1600,
    slot: "Карточка — Бусина Дзи из метеорита Алетай",
    props: {
      background: "kit-scenes-hs/scene_020.jpg",
      photo: "kit-scenes-hs/scene_020.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Книга небесного железа", title: "БУСИНА ДЗИ",
      subtitle: "резьба вручную по метеоритному железу",
      meta: "Метеорит Aletai · Китай · 1898", note: "Ручная резьба", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-021", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Царёв каменный, коллекционный образец",
    props: {
      background: "kit-scenes-hs/scene_021.jpg",
      photo: "kit-scenes-hs/scene_021.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "ЦАРЁВ",
      subtitle: "каменный метеорит",
      meta: "Волгоградская область · 1968", note: "Вес: 29,3 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-022", width: 1200, height: 1600,
    slot: "Карточка — Кулон Чжун Куй из индошинита, амулет защиты, о",
    props: {
      background: "kit-scenes-hs/scene_022.jpg",
      photo: "kit-scenes-hs/scene_022.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Книга небесного железа", title: "ЧЖУН КУЙ",
      subtitle: "резьба вручную по метеоритному железу",
      meta: "Индошинит · Юго-Восточная Азия", note: "Ручная резьба", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-023", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Дронино железный коллекционный образе",
    props: {
      background: "kit-scenes-hs/scene_023.jpg",
      photo: "kit-scenes-hs/scene_023.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "ДРОНИНО",
      subtitle: "железный метеорит",
      meta: "Рязанская область · 2000", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-024", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь коллекционный образец 12",
    props: {
      background: "kit-scenes-hs/scene_024.jpg",
      photo: "kit-scenes-hs/scene_024.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "коллекционный образец",
      meta: "Приморский край · 1947", note: "Вес: 12 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-025", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь железный, образец 19,4 г",
    props: {
      background: "kit-scenes-hs/scene_025.jpg",
      photo: "kit-scenes-hs/scene_025.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "железный метеорит",
      meta: "Приморский край · 1947", note: "Вес: 19,4 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-026", width: 1200, height: 1600,
    slot: "Карточка — Фигурка Будда из каменного метеорита, коллекци",
    props: {
      background: "kit-scenes-hs/scene_026.jpg",
      photo: "kit-scenes-hs/scene_026.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Книга небесного железа", title: "БУДДА",
      subtitle: "резьба вручную по метеоритному железу",
      meta: "Ручная работа · Краснодар", note: "Ручная резьба", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-027", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Дронино железный, коллекционный образ",
    props: {
      background: "kit-scenes-hs/scene_027.jpg",
      photo: "kit-scenes-hs/scene_027.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Коллекционные образцы", title: "ДРОНИНО",
      subtitle: "железный метеорит",
      meta: "Рязанская область · 2000", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-028", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Царёв каменный образец 30 гр, оберег ",
    props: {
      background: "kit-scenes-hs/scene_028.jpg",
      photo: "kit-scenes-hs/scene_028.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "ЦАРЁВ",
      subtitle: "каменный метеорит",
      meta: "Волгоградская область · 1968", note: "Вес: 30 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-029", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Кампо-дель-Сьело железный коллекционн",
    props: {
      background: "kit-scenes-hs/scene_029.jpg",
      photo: "kit-scenes-hs/scene_029.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "КАМПО-ДЕЛЬ-СЬЕЛО",
      subtitle: "железный метеорит",
      meta: "Аргентина · 1576", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-030", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Царёв каменный образец 64 гр, оберег ",
    props: {
      background: "kit-scenes-hs/scene_030.jpg",
      photo: "kit-scenes-hs/scene_030.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "ЦАРЁВ",
      subtitle: "каменный метеорит",
      meta: "Волгоградская область · 1968", note: "Вес: 64 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-031", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Дронино железный, коллекционный образ",
    props: {
      background: "kit-scenes-hs/scene_031.jpg",
      photo: "kit-scenes-hs/scene_031.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "ДРОНИНО",
      subtitle: "железный метеорит",
      meta: "Рязанская область · 2000", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-032", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь коллекционный образец 24",
    props: {
      background: "kit-scenes-hs/scene_032.jpg",
      photo: "kit-scenes-hs/scene_032.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "коллекционный образец",
      meta: "Приморский край · 1947", note: "Вес: 24 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-033", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Кампо-дель-Сьело железный образец 27,",
    props: {
      background: "kit-scenes-hs/scene_033.jpg",
      photo: "kit-scenes-hs/scene_033.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Коллекционные образцы", title: "КАМПО-ДЕЛЬ-СЬЕЛО",
      subtitle: "железный метеорит",
      meta: "Аргентина · 1576", note: "Вес: 27,1 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-034", width: 1200, height: 1600,
    slot: "Карточка — Браслет Синергия с метеоритом Алетай и лабрадо",
    props: {
      background: "kit-scenes-hs/scene_034.jpg",
      photo: "kit-scenes-hs/scene_034.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Украшения", title: "СИНЕРГИЯ",
      subtitle: "ручная сборка, натуральный камень и метеорит",
      meta: "Метеорит Aletai · Китай · 1898", note: "Размер подбираем по запястью", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-036", width: 1200, height: 1600,
    slot: "Карточка — Подвеска женская Сияние с метеоритом Муонионал",
    props: {
      background: "kit-scenes-hs/scene_036.jpg",
      photo: "kit-scenes-hs/scene_036.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Украшения", title: "МУОНИОНАЛУСТА",
      subtitle: "оправа ручной работы, метеоритная вставка",
      meta: "Швеция · 1906", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-037", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Царёв каменный образец 119 гр, подаро",
    props: {
      background: "kit-scenes-hs/scene_037.jpg",
      photo: "kit-scenes-hs/scene_037.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "ЦАРЁВ",
      subtitle: "каменный метеорит",
      meta: "Волгоградская область · 1968", note: "Вес: 119 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-038", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь железный, коллекционный ",
    props: {
      background: "kit-scenes-hs/scene_038.jpg",
      photo: "kit-scenes-hs/scene_038.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "железный метеорит",
      meta: "Приморский край · 1947", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-039", width: 1200, height: 1600,
    slot: "Карточка — Кулон Дракон из метеорита Алетай, амулет обере",
    props: {
      background: "kit-scenes-hs/scene_039.jpg",
      photo: "kit-scenes-hs/scene_039.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Книга небесного железа", title: "ДРАКОН",
      subtitle: "резьба вручную по метеоритному железу",
      meta: "Метеорит Aletai · Китай · 1898", note: "Ручная резьба", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-040", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Царёв каменный образец 33 гр, оберег ",
    props: {
      background: "kit-scenes-hs/scene_040.jpg",
      photo: "kit-scenes-hs/scene_040.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "ЦАРЁВ",
      subtitle: "каменный метеорит",
      meta: "Волгоградская область · 1968", note: "Вес: 33 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-041", width: 1200, height: 1600,
    slot: "Карточка — Бусина Дзи 9 глаз из метеорита Алетай, амулет ",
    props: {
      background: "kit-scenes-hs/scene_041.jpg",
      photo: "kit-scenes-hs/scene_041.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Книга небесного железа", title: "ДЕВЯТЬ ГЛАЗ",
      subtitle: "резьба вручную по метеоритному железу",
      meta: "Метеорит Aletai · Китай · 1898", note: "Ручная резьба", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-042", width: 1200, height: 1600,
    slot: "Карточка — Кулон из метеорита Алетай, оберег амулет",
    props: {
      background: "kit-scenes-hs/scene_042.jpg",
      photo: "kit-scenes-hs/scene_042.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Украшения", title: "ALETAI",
      subtitle: "оправа ручной работы, метеоритная вставка",
      meta: "Китай · 1898", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-044", width: 1200, height: 1600,
    slot: "Карточка — Подвеска Манджушри из метеорита Алетай, амулет",
    props: {
      background: "kit-scenes-hs/scene_044.jpg",
      photo: "kit-scenes-hs/scene_044.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Книга небесного железа", title: "МАНДЖУШРИ",
      subtitle: "резьба вручную по метеоритному железу",
      meta: "Метеорит Aletai · Китай · 1898", note: "Ручная резьба", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-045", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Дронино железный, коллекционный образ",
    props: {
      background: "kit-scenes-hs/scene_045.jpg",
      photo: "kit-scenes-hs/scene_045.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "ДРОНИНО",
      subtitle: "железный метеорит",
      meta: "Рязанская область · 2000", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-046", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Кампо-дель-Сьело железный образец 23,",
    props: {
      background: "kit-scenes-hs/scene_046.jpg",
      photo: "kit-scenes-hs/scene_046.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "КАМПО-ДЕЛЬ-СЬЕЛО",
      subtitle: "железный метеорит",
      meta: "Аргентина · 1576", note: "Вес: 23,2 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-047", width: 1200, height: 1600,
    slot: "Карточка — Крест с метеоритом Муонионалуста, подвеска обе",
    props: {
      background: "kit-scenes-hs/scene_047.jpg",
      photo: "kit-scenes-hs/scene_047.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Украшения", title: "МУОНИОНАЛУСТА",
      subtitle: "оправа ручной работы, метеоритная вставка",
      meta: "Швеция · 1906", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-048", width: 1200, height: 1600,
    slot: "Карточка — Подвеска женская мелонг из метеорита Алетай, а",
    props: {
      background: "kit-scenes-hs/scene_048.jpg",
      photo: "kit-scenes-hs/scene_048.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Книга небесного железа", title: "МЕЛОНГ",
      subtitle: "резьба вручную по метеоритному железу",
      meta: "Метеорит Aletai · Китай · 1898", note: "Ручная резьба", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-049", width: 1200, height: 1600,
    slot: "Карточка — Подвеска с метеоритом Муонионалуста и Молдавит",
    props: {
      background: "kit-scenes-hs/scene_049.jpg",
      photo: "kit-scenes-hs/scene_049.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Украшения", title: "МУОНИОНАЛУСТА",
      subtitle: "оправа ручной работы, метеоритная вставка",
      meta: "Швеция · 1906", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-050", width: 1200, height: 1600,
    slot: "Карточка — Кулон Чжун Куй из индошинита, амулет защиты, о",
    props: {
      background: "kit-scenes-hs/scene_050.jpg",
      photo: "kit-scenes-hs/scene_050.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Книга небесного железа", title: "ЧЖУН КУЙ",
      subtitle: "резьба вручную по метеоритному железу",
      meta: "Индошинит · Юго-Восточная Азия", note: "Ручная резьба", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-052", width: 1200, height: 1600,
    slot: "Карточка — Подвеска с метеоритом",
    props: {
      background: "kit-scenes-hs/scene_052.jpg",
      photo: "kit-scenes-hs/scene_052.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Украшения", title: "ПОДВЕСКА",
      subtitle: "оправа ручной работы, метеоритная вставка",
      meta: "Ручная работа · Краснодар", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-053", width: 1200, height: 1600,
    slot: "Карточка — Кулон \"Денежный страж\" из метеорита Муонионалу",
    props: {
      background: "kit-scenes-hs/scene_053.jpg",
      photo: "kit-scenes-hs/scene_053.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Украшения", title: "ДЕНЕЖНЫЙ СТРАЖ",
      subtitle: "оправа ручной работы, метеоритная вставка",
      meta: "Швеция · 1906", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-054", width: 1200, height: 1600,
    slot: "Карточка — Подвеска с метеоритом Серичо",
    props: {
      background: "kit-scenes-hs/scene_054.jpg",
      photo: "kit-scenes-hs/scene_054.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Украшения", title: "SERICHO",
      subtitle: "оправа ручной работы, метеоритная вставка",
      meta: "Кения · 2016", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-056", width: 1200, height: 1600,
    slot: "Карточка — Браслет из индошинита с бусиной Дзи, натуральн",
    props: {
      background: "kit-scenes-hs/scene_056.jpg",
      photo: "kit-scenes-hs/scene_056.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Украшения", title: "ИНДОШИНИТ",
      subtitle: "ручная сборка, натуральный камень и метеорит",
      meta: "Индошинит · Юго-Восточная Азия", note: "Размер подбираем по запястью", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-057", width: 1200, height: 1600,
    slot: "Карточка — Фигурка Будда из каменного метеорита, 77,3 гр,",
    props: {
      background: "kit-scenes-hs/scene_057.jpg",
      photo: "kit-scenes-hs/scene_057.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Книга небесного железа", title: "БУДДА",
      subtitle: "резьба вручную по метеоритному железу",
      meta: "Ручная работа · Краснодар", note: "Вес: 77,3 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-058", width: 1200, height: 1600,
    slot: "Карточка — Кулон женский из метеорита Алетай, амулет обер",
    props: {
      background: "kit-scenes-hs/scene_058.jpg",
      photo: "kit-scenes-hs/scene_058.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Украшения", title: "ALETAI",
      subtitle: "оправа ручной работы, метеоритная вставка",
      meta: "Китай · 1898", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-059", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Дронино железный коллекционный образе",
    props: {
      background: "kit-scenes-hs/scene_059.jpg",
      photo: "kit-scenes-hs/scene_059.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Коллекционные образцы", title: "ДРОНИНО",
      subtitle: "железный метеорит",
      meta: "Рязанская область · 2000", note: "Вес: 60,2 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-060", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь железный, осколок, образ",
    props: {
      background: "kit-scenes-hs/scene_060.jpg",
      photo: "kit-scenes-hs/scene_060.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "железный метеорит",
      meta: "Приморский край · 1947", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-061", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Каньон Дьябло - коллекционный образец",
    props: {
      background: "kit-scenes-hs/scene_061.jpg",
      photo: "kit-scenes-hs/scene_061.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Коллекционные образцы", title: "КАНЬОН ДЬЯБЛО",
      subtitle: "коллекционный образец",
      meta: "Аризона, США · 1891", note: "Вес: 14,2 г", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-062", width: 1200, height: 1600,
    slot: "Карточка — Подвеска с метеоритом Серичо",
    props: {
      background: "kit-scenes-hs/scene_062.jpg",
      photo: "kit-scenes-hs/scene_062.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Украшения", title: "SERICHO",
      subtitle: "оправа ручной работы, метеоритная вставка",
      meta: "Кения · 2016", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-063", width: 1200, height: 1600,
    slot: "Карточка — Кулон Пи Яо из метеорита Алетай, амулет изобил",
    props: {
      background: "kit-scenes-hs/scene_063.jpg",
      photo: "kit-scenes-hs/scene_063.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Книга небесного железа", title: "ПИ ЯО",
      subtitle: "резьба вручную по метеоритному железу",
      meta: "Метеорит Aletai · Китай · 1898", note: "Ручная резьба", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-064", width: 1200, height: 1600,
    slot: "Карточка — Браслет Вершитель с метеоритом Муонионалуста и",
    props: {
      background: "kit-scenes-hs/scene_064.jpg",
      photo: "kit-scenes-hs/scene_064.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Украшения", title: "ВЕРШИТЕЛЬ",
      subtitle: "ручная сборка, натуральный камень и метеорит",
      meta: "Швеция · 1906", note: "Размер подбираем по запястью", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-065", width: 1200, height: 1600,
    slot: "Карточка — Браслет \"Мудрость Будды\" с бусиной и мантрой д",
    props: {
      background: "kit-scenes-hs/scene_065.jpg",
      photo: "kit-scenes-hs/scene_065.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Украшения", title: "МУДРОСТЬ БУДДЫ",
      subtitle: "ручная сборка, натуральный камень и метеорит",
      meta: "Ручная работа · Краснодар", note: "Размер подбираем по запястью", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-066", width: 1200, height: 1600,
    slot: "Карточка — Браслет Синергия с метеоритом Алетай и лабрадо",
    props: {
      background: "kit-scenes-hs/scene_066.jpg",
      photo: "kit-scenes-hs/scene_066.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Украшения", title: "СИНЕРГИЯ",
      subtitle: "ручная сборка, натуральный камень и метеорит",
      meta: "Метеорит Aletai · Китай · 1898", note: "Размер подбираем по запястью", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-067", width: 1200, height: 1600,
    slot: "Карточка — Браслет Звёздный маг с метеоритом Алетай и бус",
    props: {
      background: "kit-scenes-hs/scene_067.jpg",
      photo: "kit-scenes-hs/scene_067.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      series: "Украшения", title: "ЗВЁЗДНЫЙ МАГ",
      subtitle: "ручная сборка, натуральный камень и метеорит",
      meta: "Метеорит Aletai · Китай · 1898", note: "Размер подбираем по запястью", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-068", width: 1200, height: 1600,
    slot: "Карточка — Серьги с Молдавитом",
    props: {
      background: "kit-scenes-hs/scene_068.jpg",
      photo: "kit-scenes-hs/scene_068.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Украшения", title: "МОЛДАВИТ",
      subtitle: "оправа ручной работы, метеоритная вставка",
      meta: "Молдавит · Чехия", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-069", width: 1200, height: 1600,
    slot: "Карточка — Серьги с Молдавитом",
    props: {
      background: "kit-scenes-hs/scene_069.jpg",
      photo: "kit-scenes-hs/scene_069.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Украшения", title: "МОЛДАВИТ",
      subtitle: "оправа ручной работы, метеоритная вставка",
      meta: "Молдавит · Чехия", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-070", width: 1200, height: 1600,
    slot: "Карточка — Подвеска с метеоритом Серичо",
    props: {
      background: "kit-scenes-hs/scene_070.jpg",
      photo: "kit-scenes-hs/scene_070.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Украшения", title: "SERICHO",
      subtitle: "оправа ручной работы, метеоритная вставка",
      meta: "Кения · 2016", 
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-071", width: 1200, height: 1600,
    slot: "Карточка — Подвеска \"Космическая удача\" с метеоритом Муон",
    props: {
      background: "kit-scenes-hs/scene_071.jpg",
      photo: "kit-scenes-hs/scene_071.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      series: "Украшения", title: "КОСМИЧЕСКАЯ УДАЧА",
      subtitle: "оправа ручной работы, метеоритная вставка",
      meta: "Швеция · 1906", 
    } as KitArtifactBannerProps,
  },
];
