import type { KitArtifactBannerProps } from "./KitArtifactBanner";
import type { ArtifactSlot } from "./artifactBanners";

/** Карточки товара на кадрах Higgsfield: изделие снято в сцене, текст поверх.
 *  Тёмное изделие -> светлая сцена (onLight), светлое изделие -> тёмная сцена.
 *
 *  Тексты сверены 13.09.2026 с главным фото WB, которое карточка заменяет:
 *  серия = категория товара на витрине, подзаголовок = что это и из чего,
 *  meta = происхождение материала, note = вес или размер с фото WB.
 *  Ничего не утверждаем сверх карточки KIT: тектит (индошинит, молдавит) не назван
 *  метеоритом, каменный метеорит не назван железом, состав браслетов по характеристикам.
 *
 *  Шаблон фиксирован: заголовок у всех карточек начинается на одной линии (TITLE_TOP
 *  в компоненте), а под неё подгоняется кадр — `bgScale` и `bgTop` двигают и масштабируют
 *  сцену так, чтобы низ изделия у всех оказался на одной высоте. `titleScale` ужимает
 *  длинные имена, чтобы заголовок остался в одну строку. Считает scripts/kit_card_layout.py. */
export const HS_CARD_SLOTS: ArtifactSlot[] = [
  {
    id: "hcard-001", width: 1200, height: 1600,
    slot: "Карточка — Шарм подвеска с Метеоритом",
    props: {
      background: "kit-scenes-hs/scene_001.jpg",
      photo: "kit-scenes-hs/scene_001.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.1055, bgTop: 0.0, titleScale: 0.761,
      series: "Подвески и кулоны", title: "ЗВЁЗДНОЕ СЕРДЦЕ",
      subtitle: "шарм со вставкой из метеорита",
      meta: "Муонионалуста · Швеция · 1906",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-002", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Царев (горбушка) 34,5 гр.",
    props: {
      background: "kit-scenes-hs/scene_002.jpg",
      photo: "kit-scenes-hs/scene_002.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.3027, bgTop: -0.3027,
      series: "Коллекционные образцы", title: "ЦАРЁВ",
      subtitle: "каменный метеорит",
      meta: "Волгоградская область · 1968", note: "Вес: 34,5 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-003", width: 1200, height: 1600,
    slot: "Карточка — Часы наручные женские с метеоритом Муонионалуста, подарок",
    props: {
      background: "kit-scenes-hs/scene_003.jpg",
      photo: "kit-scenes-hs/scene_003.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.1333, bgTop: -0.1333, titleScale: 0.777,
      series: "Часы наручные", title: "МУОНИОНАЛУСТА",
      subtitle: "часы со вставкой из метеорита",
      meta: "Швеция · 1906",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-004", width: 1200, height: 1600,
    slot: "Карточка — Браслет из натуральных камней с метеоритом Муонионалуста",
    props: {
      background: "kit-scenes-hs/scene_004.jpg",
      photo: "kit-scenes-hs/scene_004.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0123, bgTop: 0.0, titleScale: 0.777,
      series: "Браслеты", title: "МУОНИОНАЛУСТА",
      subtitle: "браслет ручной сборки с метеоритом",
      meta: "Норботтен, Швеция · 1906", note: "Размер подбираем по запястью",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-005", width: 1200, height: 1600,
    slot: "Карточка — Мужской браслет Прометей лабрадорит с метеоритом Алетай",
    props: {
      background: "kit-scenes-hs/scene_005.jpg",
      photo: "kit-scenes-hs/scene_005.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0855, bgTop: 0.0,
      series: "Браслеты", title: "ПРОМЕТЕЙ",
      subtitle: "браслет ручной сборки с метеоритом",
      meta: "Метеорит Aletai · Китай · 1898", note: "Размер подбираем по запястью",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-006", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Дронино железный коллекционный образец 27,8 гр",
    props: {
      background: "kit-scenes-hs/scene_006.jpg",
      photo: "kit-scenes-hs/scene_006.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.3386, bgTop: -0.3386,
      series: "Коллекционные образцы", title: "ДРОНИНО",
      subtitle: "железный метеорит",
      meta: "Рязанская область · 2000", note: "Вес: 27,8 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-007", width: 1200, height: 1600,
    slot: "Карточка — Бусина Дзи 9 глаз метеорит Алетай, золото, амулет оберег",
    props: {
      background: "kit-scenes-hs/scene_007.jpg",
      photo: "kit-scenes-hs/scene_007.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.1111, bgTop: 0.0,
      series: "Амулеты и обереги", title: "ДЕВЯТЬ ГЛАЗ",
      subtitle: "бусина Дзи из метеоритного железа",
      meta: "Метеорит Aletai · Китай · 1898", note: "Ручная резьба",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-008", width: 1200, height: 1600,
    slot: "Карточка — Браслет женский Сердце Будды с метеоритом Алетай и Дзи",
    props: {
      background: "kit-scenes-hs/scene_008.jpg",
      photo: "kit-scenes-hs/scene_008.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.2143, bgTop: -0.2143,
      series: "Браслеты", title: "СЕРДЦЕ БУДДЫ",
      subtitle: "браслет с метеоритом Алетай и бусиной Дзи",
      meta: "Метеорит Aletai · Китай · 1898", note: "Размер подбираем по запястью",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-009", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь железный, образец 55,7 гр, оберег",
    props: {
      background: "kit-scenes-hs/scene_009.jpg",
      photo: "kit-scenes-hs/scene_009.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0759, bgTop: -0.0759,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "железный метеорит",
      meta: "Приморский край · 1947", note: "Вес: 55,7 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-010", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь железный, образец 31,1 гр, оберег",
    props: {
      background: "kit-scenes-hs/scene_010.jpg",
      photo: "kit-scenes-hs/scene_010.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.3821, bgTop: -0.3821,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "железный метеорит",
      meta: "Приморский край · 1947", note: "Вес: 31,1 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-011", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Дронино железный, коллекционный образец №4",
    props: {
      background: "kit-scenes-hs/scene_011.jpg",
      photo: "kit-scenes-hs/scene_011.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.051, bgTop: 0.0,
      series: "Коллекционные образцы", title: "ДРОНИНО",
      subtitle: "железный метеорит",
      meta: "Рязанская область · 2000", note: "Вес: 24,2 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-012", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Царёв каменный образец 34 гр, оберег подарок",
    props: {
      background: "kit-scenes-hs/scene_012.jpg",
      photo: "kit-scenes-hs/scene_012.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0645, bgTop: -0.0,
      series: "Коллекционные образцы", title: "ЦАРЁВ",
      subtitle: "каменный метеорит",
      meta: "Волгоградская область · 1968", note: "Вес: 34 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-013", width: 1200, height: 1600,
    slot: "Карточка — Кулон-амулет паук из индошинита, тектит, оберег талисман",
    props: {
      background: "kit-scenes-hs/scene_013.jpg",
      photo: "kit-scenes-hs/scene_013.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0149, bgTop: -0.0149,
      series: "Амулеты и обереги", title: "ПАУК",
      subtitle: "резьба по индошиниту, тектит",
      meta: "Индошинит · Юго-Восточная Азия", note: "Ручная резьба",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-014", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь железный, коллекционный образец №5",
    props: {
      background: "kit-scenes-hs/scene_014.jpg",
      photo: "kit-scenes-hs/scene_014.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0897, bgTop: -0.0897,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "железный метеорит",
      meta: "Приморский край · 1947", note: "Вес: 50 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-015", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь железный коллекционный, оберег",
    props: {
      background: "kit-scenes-hs/scene_015.jpg",
      photo: "kit-scenes-hs/scene_015.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0241, bgTop: -0.0241,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "железный метеорит",
      meta: "Приморский край · 1947", note: "Вес: 35,3 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-016", width: 1200, height: 1600,
    slot: "Карточка — Мужской браслет из натуральных камней с метеоритом Алетай",
    props: {
      background: "kit-scenes-hs/scene_016.jpg",
      photo: "kit-scenes-hs/scene_016.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.0625, bgTop: -0.0625,
      series: "Браслеты", title: "ALETAI",
      subtitle: "браслет ручной сборки с метеоритом",
      meta: "Китай · 1898", note: "Размер подбираем по запястью",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-018", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Дронино железный, коллекционный образец 62,1 гр",
    props: {
      background: "kit-scenes-hs/scene_018.jpg",
      photo: "kit-scenes-hs/scene_018.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.0061, bgTop: 0.0,
      series: "Коллекционные образцы", title: "ДРОНИНО",
      subtitle: "железный метеорит",
      meta: "Рязанская область · 2000", note: "Вес: 62,1 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-019", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь железный, коллекционный образец №4",
    props: {
      background: "kit-scenes-hs/scene_019.jpg",
      photo: "kit-scenes-hs/scene_019.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.1074, bgTop: 0.0,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "железный метеорит",
      meta: "Приморский край · 1947", note: "Вес: 28 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-020", width: 1200, height: 1600,
    slot: "Карточка — Бусина Дзи из метеорита Алетай",
    props: {
      background: "kit-scenes-hs/scene_020.jpg",
      photo: "kit-scenes-hs/scene_020.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.0303, bgTop: -0.0303,
      series: "Амулеты и обереги", title: "ДЕВЯТЬ ГЛАЗ",
      subtitle: "бусина Дзи из метеоритного железа",
      meta: "Метеорит Aletai · Китай · 1898", note: "Ручная резьба",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-021", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Царёв каменный, коллекционный образец 29,3 гр",
    props: {
      background: "kit-scenes-hs/scene_021.jpg",
      photo: "kit-scenes-hs/scene_021.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.046, bgTop: 0.0,
      series: "Коллекционные образцы", title: "ЦАРЁВ",
      subtitle: "каменный метеорит",
      meta: "Волгоградская область · 1968", note: "Вес: 29,3 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-022", width: 1200, height: 1600,
    slot: "Карточка — Кулон Чжун Куй из индошинита, амулет защиты, оберег резной",
    props: {
      background: "kit-scenes-hs/scene_022.jpg",
      photo: "kit-scenes-hs/scene_022.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0429, bgTop: -0.0429,
      series: "Амулеты и обереги", title: "ЧЖУН КУЙ",
      subtitle: "резьба по индошиниту, тектит",
      meta: "Индошинит · Юго-Восточная Азия", note: "Ручная резьба",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-023", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Дронино железный коллекционный образец, подарок",
    props: {
      background: "kit-scenes-hs/scene_023.jpg",
      photo: "kit-scenes-hs/scene_023.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0046, bgTop: 0.0,
      series: "Коллекционные образцы", title: "ДРОНИНО",
      subtitle: "железный метеорит",
      meta: "Рязанская область · 2000", note: "Вес: 37,8 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-024", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь коллекционный образец 12 гр, оберег",
    props: {
      background: "kit-scenes-hs/scene_024.jpg",
      photo: "kit-scenes-hs/scene_024.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0476, bgTop: 0.0,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "железный метеорит",
      meta: "Приморский край · 1947", note: "Вес: 12 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-025", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь железный, образец 19,4 гр, оберег",
    props: {
      background: "kit-scenes-hs/scene_025.jpg",
      photo: "kit-scenes-hs/scene_025.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.082, bgTop: 0.0,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "железный метеорит",
      meta: "Приморский край · 1947", note: "Вес: 19,4 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-026", width: 1200, height: 1600,
    slot: "Карточка — Фигурка Будда из каменного метеорита, коллекционная, оберег",
    props: {
      background: "kit-scenes-hs/scene_026.jpg",
      photo: "kit-scenes-hs/scene_026.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0828, bgTop: -0.0828,
      series: "Амулеты и обереги", title: "БУДДА",
      subtitle: "резьба по каменному метеориту",
      meta: "Ordinary chondrite", note: "Вес: 46,8 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-027", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Дронино железный, коллекционный образец №5",
    props: {
      background: "kit-scenes-hs/scene_027.jpg",
      photo: "kit-scenes-hs/scene_027.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.0493, bgTop: 0.0,
      series: "Коллекционные образцы", title: "ДРОНИНО",
      subtitle: "железный метеорит",
      meta: "Рязанская область · 2000", note: "Вес: 34 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-028", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Царёв каменный образец 30 гр, оберег коллекционный",
    props: {
      background: "kit-scenes-hs/scene_028.jpg",
      photo: "kit-scenes-hs/scene_028.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0625, bgTop: -0.0625,
      series: "Коллекционные образцы", title: "ЦАРЁВ",
      subtitle: "каменный метеорит",
      meta: "Волгоградская область · 1968", note: "Вес: 30 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-029", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Кампо-дель-Сьело железный коллекционный образец",
    props: {
      background: "kit-scenes-hs/scene_029.jpg",
      photo: "kit-scenes-hs/scene_029.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0217, bgTop: 0.0, titleScale: 0.742,
      series: "Коллекционные образцы", title: "КАМПО-ДЕЛЬ-СЬЕЛО",
      subtitle: "железный метеорит",
      meta: "Аргентина · 1576", note: "Вес: 114,4 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-030", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Царёв каменный образец 64 гр, оберег подарок",
    props: {
      background: "kit-scenes-hs/scene_030.jpg",
      photo: "kit-scenes-hs/scene_030.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0, bgTop: 0.0,
      series: "Коллекционные образцы", title: "ЦАРЁВ",
      subtitle: "каменный метеорит",
      meta: "Волгоградская область · 1968", note: "Вес: 64 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-031", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Дронино железный, коллекционный образец №7",
    props: {
      background: "kit-scenes-hs/scene_031.jpg",
      photo: "kit-scenes-hs/scene_031.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.1684, bgTop: -0.1684,
      series: "Коллекционные образцы", title: "ДРОНИНО",
      subtitle: "железный метеорит",
      meta: "Рязанская область · 2000", note: "Вес: 27 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-032", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь коллекционный образец 24 гр, оберег",
    props: {
      background: "kit-scenes-hs/scene_032.jpg",
      photo: "kit-scenes-hs/scene_032.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.1644, bgTop: -0.1644,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "железный метеорит",
      meta: "Приморский край · 1947", note: "Вес: 24 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-033", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Кампо-дель-Сьело железный образец 27,1 гр, оберег",
    props: {
      background: "kit-scenes-hs/scene_033.jpg",
      photo: "kit-scenes-hs/scene_033.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.003, bgTop: 0.0, titleScale: 0.742,
      series: "Коллекционные образцы", title: "КАМПО-ДЕЛЬ-СЬЕЛО",
      subtitle: "железный метеорит",
      meta: "Аргентина · 1576", note: "Вес: 27,1 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-034", width: 1200, height: 1600,
    slot: "Карточка — Браслет Синергия с метеоритом Алетай и лабрадоритом",
    props: {
      background: "kit-scenes-hs/scene_034.jpg",
      photo: "kit-scenes-hs/scene_034.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0476, bgTop: 0.0,
      series: "Браслеты", title: "СИНЕРГИЯ",
      subtitle: "браслет ручной сборки с метеоритом",
      meta: "Метеорит Aletai · Китай · 1898", note: "Размер подбираем по запястью",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-036", width: 1200, height: 1600,
    slot: "Карточка — Подвеска женская Сияние с метеоритом Муонионалуста, оберег",
    props: {
      background: "kit-scenes-hs/scene_036.jpg",
      photo: "kit-scenes-hs/scene_036.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.0493, bgTop: 0.0,
      series: "Подвески и кулоны", title: "СИЯНИЕ",
      subtitle: "подвеска со вставкой из метеорита",
      meta: "Муонионалуста · Швеция · 1906",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-037", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Царёв каменный образец 119 гр, подарок мужчине",
    props: {
      background: "kit-scenes-hs/scene_037.jpg",
      photo: "kit-scenes-hs/scene_037.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0149, bgTop: -0.0149,
      series: "Коллекционные образцы", title: "ЦАРЁВ",
      subtitle: "каменный метеорит",
      meta: "Волгоградская область · 1968", note: "Вес: 119 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-038", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь железный, коллекционный образец №2",
    props: {
      background: "kit-scenes-hs/scene_038.jpg",
      photo: "kit-scenes-hs/scene_038.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.2928, bgTop: -0.2928,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "железный метеорит",
      meta: "Приморский край · 1947", note: "Вес: 45,1 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-039", width: 1200, height: 1600,
    slot: "Карточка — Кулон Дракон из метеорита Алетай, амулет оберег резной",
    props: {
      background: "kit-scenes-hs/scene_039.jpg",
      photo: "kit-scenes-hs/scene_039.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.1371, bgTop: -0.1371,
      series: "Амулеты и обереги", title: "ДРАКОН",
      subtitle: "резьба по метеоритному железу",
      meta: "Метеорит Aletai · Китай · 1898", note: "Ручная резьба",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-040", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Царёв каменный образец 33 гр, оберег коллекционный",
    props: {
      background: "kit-scenes-hs/scene_040.jpg",
      photo: "kit-scenes-hs/scene_040.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0312, bgTop: 0.0,
      series: "Коллекционные образцы", title: "ЦАРЁВ",
      subtitle: "каменный метеорит",
      meta: "Волгоградская область · 1968", note: "Вес: 33 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-041", width: 1200, height: 1600,
    slot: "Карточка — Бусина Дзи 9 глаз из метеорита Алетай, амулет оберег",
    props: {
      background: "kit-scenes-hs/scene_041.jpg",
      photo: "kit-scenes-hs/scene_041.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.0909, bgTop: 0.0,
      series: "Амулеты и обереги", title: "ДЕВЯТЬ ГЛАЗ",
      subtitle: "бусина Дзи из метеоритного железа",
      meta: "Метеорит Aletai · Китай · 1898", note: "Ручная резьба",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-042", width: 1200, height: 1600,
    slot: "Карточка — Кулон из метеорита Алетай, оберег амулет",
    props: {
      background: "kit-scenes-hs/scene_042.jpg",
      photo: "kit-scenes-hs/scene_042.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.1333, bgTop: -0.1333, titleScale: 0.756,
      series: "Подвески и кулоны", title: "АВАЛОКИТЕШВАРА",
      subtitle: "кулон из цельного метеоритного железа",
      meta: "Метеорит Aletai · Китай · 1898", note: "Вес: 46,2 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-044", width: 1200, height: 1600,
    slot: "Карточка — Подвеска Манджушри из метеорита Алетай, амулет оберег",
    props: {
      background: "kit-scenes-hs/scene_044.jpg",
      photo: "kit-scenes-hs/scene_044.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.041, bgTop: 0.0,
      series: "Амулеты и обереги", title: "МАНДЖУШРИ",
      subtitle: "резьба по метеоритному железу",
      meta: "Метеорит Aletai · Китай · 1898", note: "Вес: 41,4 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-045", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Дронино железный, коллекционный образец №1",
    props: {
      background: "kit-scenes-hs/scene_045.jpg",
      photo: "kit-scenes-hs/scene_045.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.1205, bgTop: 0.0,
      series: "Коллекционные образцы", title: "ДРОНИНО",
      subtitle: "железный метеорит",
      meta: "Рязанская область · 2000", note: "Вес: 19,1 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-046", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Кампо-дель-Сьело железный образец 23,2 гр, оберег",
    props: {
      background: "kit-scenes-hs/scene_046.jpg",
      photo: "kit-scenes-hs/scene_046.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.2409, bgTop: -0.2409, titleScale: 0.742,
      series: "Коллекционные образцы", title: "КАМПО-ДЕЛЬ-СЬЕЛО",
      subtitle: "железный метеорит",
      meta: "Аргентина · 1576", note: "Вес: 23,2 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-047", width: 1200, height: 1600,
    slot: "Карточка — Крест с метеоритом Муонионалуста, подвеска оберег",
    props: {
      background: "kit-scenes-hs/scene_047.jpg",
      photo: "kit-scenes-hs/scene_047.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.3178, bgTop: -0.3178, titleScale: 0.73,
      series: "Подвески и кулоны", title: "НОРДИЧЕСКИЙ КРЕСТ",
      subtitle: "крест из метеоритного железа",
      meta: "Муонионалуста · Швеция · 1906",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-048", width: 1200, height: 1600,
    slot: "Карточка — Подвеска женская мелонг из метеорита Алетай, амулет оберег",
    props: {
      background: "kit-scenes-hs/scene_048.jpg",
      photo: "kit-scenes-hs/scene_048.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.4167, bgTop: -0.4167,
      series: "Амулеты и обереги", title: "МЕЛОНГ",
      subtitle: "резьба по метеоритному железу",
      meta: "Метеорит Aletai · Китай · 1898", note: "Вес: 53 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-049", width: 1200, height: 1600,
    slot: "Карточка — Подвеска с метеоритом Муонионалуста и Молдавитом",
    props: {
      background: "kit-scenes-hs/scene_049.jpg",
      photo: "kit-scenes-hs/scene_049.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.164, bgTop: 0.0, titleScale: 0.777,
      series: "Подвески и кулоны", title: "МУОНИОНАЛУСТА",
      subtitle: "подвеска с метеоритом и молдавитом",
      meta: "Швеция · 1906", note: "Диаметр: 21 мм",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-050", width: 1200, height: 1600,
    slot: "Карточка — Кулон Чжун Куй из индошинита, амулет защиты, оберег",
    props: {
      background: "kit-scenes-hs/scene_050.jpg",
      photo: "kit-scenes-hs/scene_050.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0345, bgTop: 0.0,
      series: "Амулеты и обереги", title: "ЧЖУН КУЙ",
      subtitle: "резьба по индошиниту, тектит",
      meta: "Индошинит · Юго-Восточная Азия", note: "Ручная резьба",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-052", width: 1200, height: 1600,
    slot: "Карточка — Подвеска с метеоритом",
    props: {
      background: "kit-scenes-hs/scene_052.jpg",
      photo: "kit-scenes-hs/scene_052.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.028, bgTop: -0.0, titleScale: 0.703,
      series: "Подвески и кулоны", title: "НЕПОБЕДИМОЕ СОЛНЦЕ",
      subtitle: "подвеска со вставкой из метеорита",
      meta: "Муонионалуста · Швеция · 1906",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-053", width: 1200, height: 1600,
    slot: "Карточка — Кулон \"Денежный страж\" из метеорита Муонионалуста",
    props: {
      background: "kit-scenes-hs/scene_053.jpg",
      photo: "kit-scenes-hs/scene_053.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.1684, bgTop: -0.1684, titleScale: 0.758,
      series: "Подвески и кулоны", title: "ДЕНЕЖНЫЙ СТРАЖ",
      subtitle: "кулон из метеоритного железа",
      meta: "Муонионалуста · Швеция · 1906",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-054", width: 1200, height: 1600,
    slot: "Карточка — Подвеска с метеоритом Серичо",
    props: {
      background: "kit-scenes-hs/scene_054.jpg",
      photo: "kit-scenes-hs/scene_054.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.1379, bgTop: 0.0,
      series: "Подвески и кулоны", title: "SERICHO",
      subtitle: "подвеска со вставкой из метеорита",
      meta: "Кения · 2016",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-056", width: 1200, height: 1600,
    slot: "Карточка — Браслет из индошинита с бусиной Дзи, натуральные камни",
    props: {
      background: "kit-scenes-hs/scene_056.jpg",
      photo: "kit-scenes-hs/scene_056.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0625, bgTop: -0.0625, titleScale: 0.706,
      series: "Браслеты", title: "ДЕВЯТЬ ГЛАЗ КОСМОСА",
      subtitle: "браслет с Дзи из индошинита и лавой",
      meta: "Индошинит · тектит", note: "Размер подбираем по запястью",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-057", width: 1200, height: 1600,
    slot: "Карточка — Фигурка Будда из каменного метеорита, 77,3 гр, оберег",
    props: {
      background: "kit-scenes-hs/scene_057.jpg",
      photo: "kit-scenes-hs/scene_057.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0559, bgTop: -0.0559,
      series: "Амулеты и обереги", title: "БУДДА",
      subtitle: "резьба по каменному метеориту",
      meta: "Ordinary chondrite", note: "Вес: 77,3 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-058", width: 1200, height: 1600,
    slot: "Карточка — Кулон женский из метеорита Алетай, амулет оберег, подарок",
    props: {
      background: "kit-scenes-hs/scene_058.jpg",
      photo: "kit-scenes-hs/scene_058.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.1333, bgTop: -0.1333,
      series: "Подвески и кулоны", title: "СУНЬ УКУН",
      subtitle: "кулон из метеоритного железа в титане",
      meta: "Метеорит Aletai · Китай · 1898", note: "Метеорит: 20 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-059", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Дронино железный коллекционный образец 60,2 гр",
    props: {
      background: "kit-scenes-hs/scene_059.jpg",
      photo: "kit-scenes-hs/scene_059.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.0154, bgTop: 0.0,
      series: "Коллекционные образцы", title: "ДРОНИНО",
      subtitle: "железный метеорит",
      meta: "Рязанская область · 2000", note: "Вес: 60,2 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-060", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Сихотэ-Алинь железный, осколок, образец",
    props: {
      background: "kit-scenes-hs/scene_060.jpg",
      photo: "kit-scenes-hs/scene_060.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.1565, bgTop: -0.1565,
      series: "Коллекционные образцы", title: "СИХОТЭ-АЛИНЬ",
      subtitle: "железный метеорит",
      meta: "Приморский край · 1947", note: "Вес: 89,2 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-061", width: 1200, height: 1600,
    slot: "Карточка — Метеорит Каньон Дьябло - коллекционный образец: 14,2 гр.",
    props: {
      background: "kit-scenes-hs/scene_061.jpg",
      photo: "kit-scenes-hs/scene_061.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.056, bgTop: 0.0, titleScale: 0.791,
      series: "Коллекционные образцы", title: "КАНЬОН ДЬЯБЛО",
      subtitle: "железный метеорит",
      meta: "Аризона, США · XIX век", note: "Вес: 14,2 г",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-062", width: 1200, height: 1600,
    slot: "Карточка — Подвеска с метеоритом Серичо",
    props: {
      background: "kit-scenes-hs/scene_062.jpg",
      photo: "kit-scenes-hs/scene_062.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0543, bgTop: -0.0,
      series: "Подвески и кулоны", title: "SERICHO",
      subtitle: "подвеска со вставкой из метеорита",
      meta: "Кения · 2016",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-063", width: 1200, height: 1600,
    slot: "Карточка — Кулон Пи Яо из метеорита Алетай, амулет изобилия, оберег",
    props: {
      background: "kit-scenes-hs/scene_063.jpg",
      photo: "kit-scenes-hs/scene_063.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.619, bgTop: -0.619,
      series: "Амулеты и обереги", title: "ПИ ЯО",
      subtitle: "резьба по метеоритному железу",
      meta: "Метеорит Aletai · Китай · 1898", note: "Ручная резьба",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-064", width: 1200, height: 1600,
    slot: "Карточка — Браслет Вершитель с метеоритом Муонионалуста и лабрадоритом",
    props: {
      background: "kit-scenes-hs/scene_064.jpg",
      photo: "kit-scenes-hs/scene_064.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.0828, bgTop: -0.0828,
      series: "Браслеты", title: "ВЕРШИТЕЛЬ",
      subtitle: "браслет ручной сборки с метеоритом",
      meta: "Муонионалуста · Швеция · 1906", note: "Размер подбираем по запястью",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-065", width: 1200, height: 1600,
    slot: "Карточка — Браслет \"Мудрость Будды\" с бусиной и мантрой для медитации",
    props: {
      background: "kit-scenes-hs/scene_065.jpg",
      photo: "kit-scenes-hs/scene_065.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.0625, bgTop: -0.0625, titleScale: 0.769,
      series: "Браслеты", title: "МУДРОСТЬ БУДДЫ",
      subtitle: "браслет из лавы, бронзита и гематита",
      meta: "Бусина Будды · Таиланд", note: "Размер подбираем по запястью",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-066", width: 1200, height: 1600,
    slot: "Карточка — Браслет Синергия с метеоритом Алетай и лабрадоритом",
    props: {
      background: "kit-scenes-hs/scene_066.jpg",
      photo: "kit-scenes-hs/scene_066.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.371, bgTop: -0.371,
      series: "Браслеты", title: "СИНЕРГИЯ",
      subtitle: "браслет ручной сборки с метеоритом",
      meta: "Метеорит Aletai · Китай · 1898", note: "Размер подбираем по запястью",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-067", width: 1200, height: 1600,
    slot: "Карточка — Браслет Звёздный маг с метеоритом Алетай и бусиной Дзи",
    props: {
      background: "kit-scenes-hs/scene_067.jpg",
      photo: "kit-scenes-hs/scene_067.jpg",
      productInBackground: true, layout: "poster", onLight: true, textScale: 1.35,
      bgScale: 1.1333, bgTop: -0.1333,
      series: "Браслеты", title: "ЗВЁЗДНЫЙ МАГ",
      subtitle: "браслет с метеоритом и бусиной Дзи",
      meta: "Метеорит Aletai · Китай · 1898", note: "Размер подбираем по запястью",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-068", width: 1200, height: 1600,
    slot: "Карточка — Серьги с Молдавитом",
    props: {
      background: "kit-scenes-hs/scene_068.jpg",
      photo: "kit-scenes-hs/scene_068.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.0749, bgTop: 0.0,
      series: "Серьги", title: "МОЛДАВИТ",
      subtitle: "серьги-пусеты с молдавитом",
      meta: "Молдавит, тектит · Чехия",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-069", width: 1200, height: 1600,
    slot: "Карточка — Серьги с Молдавитом",
    props: {
      background: "kit-scenes-hs/scene_069.jpg",
      photo: "kit-scenes-hs/scene_069.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.1786, bgTop: 0.0,
      series: "Серьги", title: "МОЛДАВИТ",
      subtitle: "серьги-пусеты с молдавитом",
      meta: "Молдавит, тектит · Чехия",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-070", width: 1200, height: 1600,
    slot: "Карточка — Подвеска с метеоритом Серичо",
    props: {
      background: "kit-scenes-hs/scene_070.jpg",
      photo: "kit-scenes-hs/scene_070.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.0692, bgTop: -0.0692,
      series: "Подвески и кулоны", title: "SERICHO",
      subtitle: "подвеска со вставкой из метеорита",
      meta: "Кения · 2016",
    } as KitArtifactBannerProps,
  },
  {
    id: "hcard-071", width: 1200, height: 1600,
    slot: "Карточка — Подвеска \"Космическая удача\" с метеоритом Муонионалуста",
    props: {
      background: "kit-scenes-hs/scene_071.jpg",
      photo: "kit-scenes-hs/scene_071.jpg",
      productInBackground: true, layout: "poster", textScale: 1.35,
      bgScale: 1.1282, bgTop: 0.0, titleScale: 0.725,
      series: "Подвески и кулоны", title: "КОСМИЧЕСКАЯ УДАЧА",
      subtitle: "подвеска со вставкой из метеорита",
      meta: "Муонионалуста · Швеция · 1906",
    } as KitArtifactBannerProps,
  },
];
